import { createSlice } from '@reduxjs/toolkit'

const initialState = {
  mode: 'light',
  user: null,
  token: null,
  cart: ['item'],
  likes: [],
  skins: [
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/10/Luxe_Ghost.png/revision/latest?cb=20210707185727',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Ghost',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a4/Luxe_Spectre.png/revision/latest?cb=20210707202048',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Spectre',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/48/Luxe_Judge.png/revision/latest?cb=20210707202111',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Judge',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e3/Luxe_Vandal.png/revision/latest?cb=20210707202151',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Vandal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/be/Luxe_Operator.png/revision/latest?cb=20210707201159',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Operator',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/79/Luxe_Knife.png/revision/latest?cb=20210707185728',
      rarity: 'Select',
      bundle: 'Luxe',
      weapon: 'Knife',
      price: 1750,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/ea/Aristocrat_Sheriff.png/revision/latest?cb=20210707202412',
      rarity: 'Deluxe',
      bundle: 'Aristocrat',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/bf/Aristocrat_Stinger.png/revision/latest?cb=20210707202424',
      rarity: 'Deluxe',
      bundle: 'Aristocrat',
      weapon: 'Stinger',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4b/Aristocrat_Bulldog.png/revision/latest?cb=20210707202437',
      rarity: 'Deluxe',
      bundle: 'Aristocrat',
      weapon: 'Bulldog',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d4/Aristocrat_Vandal.png/revision/latest?cb=20210707202447',
      rarity: 'Deluxe',
      bundle: 'Aristocrat',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/8c/Aristocrat_Ares.png/revision/latest?cb=20210707202459',
      rarity: 'Deluxe',
      bundle: 'Aristocrat',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f8/Galleria_Classic.png/revision/latest?cb=20200701232133',
      rarity: 'Select',
      bundle: 'Galleria',
      weapon: 'Classic',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/37/Galleria_Bucky.png/revision/latest?cb=20210707202659',
      rarity: 'Select',
      bundle: 'Galleria',
      weapon: 'Bucky',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/60/Galleria_Guardian.png/revision/latest?cb=20210707202728',
      rarity: 'Select',
      bundle: 'Galleria',
      weapon: 'Guardian',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ac/Galleria_Phantom.png/revision/latest?cb=20210707202756',
      rarity: 'Select',
      bundle: 'Galleria',
      weapon: 'Phantom',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/78/Galleria_Marshal.png/revision/latest?cb=20210707202809',
      rarity: 'Select',
      bundle: 'Galleria',
      weapon: 'Marshal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3b/Rush_Frenzy.png/revision/latest?cb=20210707202952',
      rarity: 'Select',
      bundle: 'Rush',
      weapon: 'Frenzy',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/15/Rush_Judge.png/revision/latest?cb=20210707203029',
      rarity: 'Select',
      bundle: 'Rush',
      weapon: 'Judge',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a7/Rush_Bulldog.png/revision/latest?cb=20210707203127',
      rarity: 'Select',
      bundle: 'Rush',
      weapon: 'Bulldog',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/14/Rush_Phantom.png/revision/latest?cb=20210707203237',
      rarity: 'Select',
      bundle: 'Rush',
      weapon: 'Phantom',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/75/Rush_Ares.png/revision/latest?cb=20210707191424',
      rarity: 'Select',
      bundle: 'Rush',
      weapon: 'Ares',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/19/Sakura_Classic.png/revision/latest?cb=20210707203326',
      rarity: 'Deluxe',
      bundle: 'Sakura',
      weapon: 'Classic',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e7/Sakura_Sheriff.png/revision/latest?cb=20210707203342',
      rarity: 'Deluxe',
      bundle: 'Sakura',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f7/Sakura_Stinger.png/revision/latest?cb=20210707203403',
      rarity: 'Deluxe',
      bundle: 'Sakura',
      weapon: 'Stinger',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5f/Sakura_Vandal.png/revision/latest?cb=20210707203414',
      rarity: 'Deluxe',
      bundle: 'Sakura',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a1/Sakura_Ares.png/revision/latest?cb=20210707203430',
      rarity: 'Deluxe',
      bundle: 'Sakura',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6a/Convex_Sheriff.png/revision/latest?cb=20210707203451',
      rarity: 'Select',
      bundle: 'Convex',
      weapon: 'Sheriff',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/05/Convex_Spectre.png/revision/latest?cb=20210707203514',
      rarity: 'Select',
      bundle: 'Convex',
      weapon: 'Spectre',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/28/Convex_Judge.png/revision/latest?cb=20210707203527',
      rarity: 'Select',
      bundle: 'Convex',
      weapon: 'Judge',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b3/Convex_Bulldog.png/revision/latest?cb=20210707203537',
      rarity: 'Select',
      bundle: 'Convex',
      weapon: 'Bulldog',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d4/Convex_Operator.png/revision/latest?cb=20210707203550',
      rarity: 'Select',
      bundle: 'Convex',
      weapon: 'Operator',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/92/Avalanche_Classic.png/revision/latest?cb=20200408115239',
      rarity: 'Deluxe',
      bundle: 'Avalanche',
      weapon: 'Classic',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f5/Avalanche_Spectre.png/revision/latest?cb=20200408121140',
      rarity: 'Deluxe',
      bundle: 'Avalanche',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9e/Avalanche_Phantom.png/revision/latest?cb=20200408121025',
      rarity: 'Deluxe',
      bundle: 'Avalanche',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b2/Avalanche_Vandal.png/revision/latest?cb=20200408121231',
      rarity: 'Deluxe',
      bundle: 'Avalanche',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f0/Avalanche_Marshal.png/revision/latest?cb=20200408120940',
      rarity: 'Deluxe',
      bundle: 'Avalanche',
      weapon: 'Marshal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cc/Prime_Classic.png/revision/latest?cb=20210707141714',
      rarity: 'Premium',
      bundle: 'Prime',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/ce/Prime_Spectre.png/revision/latest?cb=20210707141713',
      rarity: 'Premium',
      bundle: 'Prime',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Prime_Guardian.png/revision/latest?cb=20210707141712',
      rarity: 'Premium',
      bundle: 'Prime',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/aa/Prime_Vandal.png/revision/latest?cb=20210707141713',
      rarity: 'Premium',
      bundle: 'Prime',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/15/Prime_Axe.png/revision/latest?cb=20210707185804',
      rarity: 'Premium',
      bundle: 'Prime',
      weapon: 'Axe',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/24/Sovereign_Ghost.png/revision/latest?cb=20210708101259',
      rarity: 'Premium',
      bundle: 'Sovereign',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9e/Sovereign_Stinger.png/revision/latest?cb=20210708101330',
      rarity: 'Premium',
      bundle: 'Sovereign',
      weapon: 'Stinger',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b3/Sovereign_Guardian.png/revision/latest?cb=20210708101356',
      rarity: 'Premium',
      bundle: 'Sovereign',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/91/Sovereign_Marshal.png/revision/latest?cb=20210708101440',
      rarity: 'Premium',
      bundle: 'Sovereign',
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cb/Sovereign_Sword.png/revision/latest?cb=20200911031827',
      rarity: 'Premium',
      bundle: 'Sovereign',
      weapon: 'Sword',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/ce/Prism_Ghost.png/revision/latest?cb=20200623202609',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Ghost',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/28/Prism_Spectre.png/revision/latest?cb=20200623202620',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d4/Prism_Phantom.png/revision/latest?cb=20200623202631',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a6/Prism_Operator.png/revision/latest?cb=20200623202641',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/dd/Prism_Ares.png/revision/latest?cb=20200623202540',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3f/Prism_Knife.png/revision/latest?cb=20210707191428',
      rarity: 'Deluxe',
      bundle: 'Prism',
      weapon: 'Knife',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c4/Elderflame_Frenzy.png/revision/latest?cb=20210707203656',
      rarity: 'Ultra',
      bundle: 'Elderflame',
      weapon: 'Frenzy',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c6/Elderflame_Judge.png/revision/latest?cb=20210707203713',
      rarity: 'Ultra',
      bundle: 'Elderflame',
      weapon: 'Judge',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d2/Elderflame_Vandal.png/revision/latest?cb=20210707203727',
      rarity: 'Ultra',
      bundle: 'Elderflame',
      weapon: 'Vandal',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/ed/Elderflame_Operator.png/revision/latest?cb=20210707203739',
      rarity: 'Ultra',
      bundle: 'Elderflame',
      weapon: 'Operator',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a9/Elderflame_Dagger.png/revision/latest?cb=20210707185625',
      rarity: 'Ultra',
      bundle: 'Elderflame',
      weapon: 'Dagger',
      price: 4950,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b7/Oni_Shorty.png/revision/latest?cb=20210708101734',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Shorty',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e8/Oni_Bucky.png/revision/latest?cb=20210708101817',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/22/Oni_Guardian.png/revision/latest?cb=20210708101852',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/65/Oni_Phantom.png/revision/latest?cb=20200911011334',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/83/Oni_Claw.png/revision/latest?cb=20210707185747',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Claw',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cd/Glitchpop_Frenzy.png/revision/latest?cb=20210708102002',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Frenzy',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e1/Glitchpop_Judge.png/revision/latest?cb=20210708102023',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Judge',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/74/Glitchpop_Bulldog.png/revision/latest?cb=20210708102012',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Bulldog',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5f/Glitchpop_Odin.png/revision/latest?cb=20210708102036',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Odin',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/55/Glitchpop_Dagger.png/revision/latest?cb=20210707185641',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Dagger',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/23/Nebula_Sheriff.png/revision/latest?cb=20210707185745',
      rarity: 'Premium',
      bundle: 'Nebula',
      weapon: 'Sheriff',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f0/Nebula_Guardian.png/revision/latest?cb=20210708102155',
      rarity: 'Premium',
      bundle: 'Nebula',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b1/Nebula_Phantom.png/revision/latest?cb=20210708102144',
      rarity: 'Premium',
      bundle: 'Nebula',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/16/Nebula_Ares.png/revision/latest?cb=20200910144659',
      rarity: 'Premium',
      bundle: 'Nebula',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/89/Nebula_Knife.png/revision/latest?cb=20210708102235',
      rarity: 'Premium',
      bundle: 'Nebula',
      weapon: 'Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/52/Spline_Classic.png/revision/latest?cb=20210708102407',
      rarity: 'Premium',
      bundle: 'Spline',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Spline_Spectre.png/revision/latest?cb=20210707191423',
      rarity: 'Premium',
      bundle: 'Spline',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4f/Spline_Phantom.png/revision/latest?cb=20210708102354',
      rarity: 'Premium',
      bundle: 'Spline',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Spline_Operator.png/revision/latest?cb=20210708102339',
      rarity: 'Premium',
      bundle: 'Spline',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b8/Spline_Dagger.png/revision/latest?cb=20210707191428',
      rarity: 'Premium',
      bundle: 'Spline',
      weapon: 'Dagger',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6f/Ego_Ghost.png/revision/latest?cb=20210707185619',
      rarity: 'Premium',
      bundle: 'Ego',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/43/Ego_Stinger.png/revision/latest?cb=20210707185623',
      rarity: 'Premium',
      bundle: 'Ego',
      weapon: 'Stinger',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/54/Ego_Guardian.png/revision/latest?cb=20210707185620',
      rarity: 'Premium',
      bundle: 'Ego',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/91/Ego_Vandal.png/revision/latest?cb=20210707185625',
      rarity: 'Premium',
      bundle: 'Ego',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6e/Ego_Knife.png/revision/latest?cb=20210707185622',
      rarity: 'Premium',
      bundle: 'Ego',
      weapon: 'Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/84/Smite_Classic.png/revision/latest?cb=20210708102637',
      rarity: 'Select',
      bundle: 'Smite',
      weapon: 'Classic',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9b/Smite_Judge.png/revision/latest?cb=20200916171804',
      rarity: 'Select',
      bundle: 'Smite',
      weapon: 'Judge',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/18/Smite_Phantom.png/revision/latest?cb=20200916171825',
      rarity: 'Select',
      bundle: 'Smite',
      weapon: 'Phantom',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/22/Smite_Odin.png/revision/latest?cb=20200916171843',
      rarity: 'Select',
      bundle: 'Smite',
      weapon: 'Odin',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/1f/Smite_Knife.png/revision/latest?cb=20200916171858',
      rarity: 'Select',
      bundle: 'Smite',
      weapon: 'Knife',
      price: 1750,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/f/f8/Gravitational_Uranium_Neuroblaster_Classic.png/revision/latest?cb=20210707185653',
      rarity: 'Premium',
      bundle: 'Gravitational Uranium Neuroblaster',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/7/72/Gravitational_Uranium_Neuroblaster_Spectre.png/revision/latest?cb=20210707185656',
      rarity: 'Premium',
      bundle: 'Gravitational Uranium Neuroblaster',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/a/ae/Gravitational_Uranium_Neuroblaster_Bucky.png/revision/latest?cb=20210707185651',
      rarity: 'Premium',
      bundle: 'Gravitational Uranium Neuroblaster',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/a/a1/Gravitational_Uranium_Neuroblaster_Operator.png/revision/latest?cb=20210707185654',
      rarity: 'Premium',
      bundle: 'Gravitational Uranium Neuroblaster',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/1/15/Gravitational_Uranium_Neuroblaster_Baton.png/revision/latest?cb=20210707185650',
      rarity: 'Premium',
      bundle: 'Gravitational Uranium Neuroblaster',
      weapon: 'Baton',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9f/Singularity_Sheriff.png/revision/latest?cb=20201010151704',
      rarity: 'Exclusive',
      bundle: 'Singularity',
      weapon: 'Sheriff',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7e/Singularity_Spectre.png/revision/latest?cb=20201010151720',
      rarity: 'Exclusive',
      bundle: 'Singularity',
      weapon: 'Spectre',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c6/Singularity_Phantom.png/revision/latest?cb=20201010151730',
      rarity: 'Exclusive',
      bundle: 'Singularity',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d5/Singularity_Ares.png/revision/latest?cb=20201010151740',
      rarity: 'Exclusive',
      bundle: 'Singularity',
      weapon: 'Ares',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/10/Singularity_Knife.png/revision/latest?cb=20210707191411',
      rarity: 'Exclusive',
      bundle: 'Singularity',
      weapon: 'Knife',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fd/Reaver_Sheriff.png/revision/latest?cb=20210708103455',
      rarity: 'Premium',
      bundle: 'Reaver',
      weapon: 'Sheriff',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cc/Reaver_Guardian.png/revision/latest?cb=20201027170547',
      rarity: 'Premium',
      bundle: 'Reaver',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/27/Reaver_Vandal.png/revision/latest?cb=20210708103519',
      rarity: 'Premium',
      bundle: 'Reaver',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e7/Reaver_Operator.png/revision/latest?cb=20201027170727',
      rarity: 'Premium',
      bundle: 'Reaver',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/71/Reaver_Knife.png/revision/latest?cb=20210708103539',
      rarity: 'Premium',
      bundle: 'Reaver',
      weapon: 'Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Ion_Sheriff.png/revision/latest?cb=20210712140421',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Sheriff',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/09/Ion_Bucky.png/revision/latest?cb=20201112142243',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/49/Ion_Phantom.png/revision/latest?cb=20201112142324',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b8/Ion_Operator.png/revision/latest?cb=20201112142312',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6f/Ion_Energy_Sword.png/revision/latest?cb=20210708103635',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Energy Sword',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9a/Wasteland_Shorty.png/revision/latest?cb=20201027171104',
      rarity: 'Deluxe',
      bundle: 'Wasteland',
      weapon: 'Shorty',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d5/Wasteland_Sheriff.png/revision/latest?cb=20210708103806',
      rarity: 'Deluxe',
      bundle: 'Wasteland',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fe/Wasteland_Spectre.png/revision/latest?cb=20201027171118',
      rarity: 'Deluxe',
      bundle: 'Wasteland',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ad/Wasteland_Vandal.png/revision/latest?cb=20201027171129',
      rarity: 'Deluxe',
      bundle: 'Wasteland',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cf/Wasteland_Marshal.png/revision/latest?cb=20201027171046',
      rarity: 'Deluxe',
      bundle: 'Wasteland',
      weapon: 'Marshal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5f/Sensation_Frenzy.png/revision/latest?cb=20210708103937',
      rarity: 'Select',
      bundle: 'Sensation',
      weapon: 'Frenzy',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e1/Sensation_Stinger.png/revision/latest?cb=20201112150323',
      rarity: 'Select',
      bundle: 'Sensation',
      weapon: 'Stinger',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/68/Sensation_Judge.png/revision/latest?cb=20201112150255',
      rarity: 'Select',
      bundle: 'Sensation',
      weapon: 'Judge',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/05/Sensation_Vandal.png/revision/latest?cb=20201112150337',
      rarity: 'Select',
      bundle: 'Sensation',
      weapon: 'Vandal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/31/Sensation_Odin.png/revision/latest?cb=20201112150309',
      rarity: 'Select',
      bundle: 'Sensation',
      weapon: 'Odin',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fe/Winterwunderland_Ghost.png/revision/latest?cb=20210708104120',
      rarity: 'Deluxe',
      bundle: 'Winterwunderland',
      weapon: 'Ghost',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3b/Winterwunderland_Phantom.png/revision/latest?cb=20210708104056',
      rarity: 'Deluxe',
      bundle: 'Winterwunderland',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f2/Winterwunderland_Vandal.png/revision/latest?cb=20210708104203',
      rarity: 'Deluxe',
      bundle: 'Winterwunderland',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/60/Winterwunderland_Marshal.png/revision/latest?cb=20210708104142',
      rarity: 'Deluxe',
      bundle: 'Winterwunderland',
      weapon: 'Marshal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/04/Winterwunderland_Candy_Cane.png/revision/latest?cb=20210707191425',
      rarity: 'Deluxe',
      bundle: 'Winterwunderland',
      weapon: 'Candy Cane',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b4/BlastX_Frenzy.png/revision/latest?cb=20210708104353',
      rarity: 'Exclusive',
      bundle: 'BlastX',
      weapon: 'Frenzy',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c6/BlastX_Spectre.png/revision/latest?cb=20210708104407',
      rarity: 'Exclusive',
      bundle: 'BlastX',
      weapon: 'Spectre',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b1/BlastX_Phantom.png/revision/latest?cb=20210708104423',
      rarity: 'Exclusive',
      bundle: 'BlastX',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/13/BlastX_Odin.png/revision/latest?cb=20201210133413',
      rarity: 'Exclusive',
      bundle: 'BlastX',
      weapon: 'Odin',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/2d/BlastX_Polymer_Knifetech_Coated_Knife.png/revision/latest?cb=20210707185605',
      rarity: 'Exclusive',
      bundle: 'BlastX',
      weapon: 'Polymer Knifetech Coated Knife',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/01/Prism_II_Shorty.png/revision/latest?cb=20230425140015',
      rarity: 'Select',
      bundle: 'Prism II',
      weapon: 'Shorty',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f9/Prism_II_Sheriff.png/revision/latest?cb=20210708104800',
      rarity: 'Select',
      bundle: 'Prism II',
      weapon: 'Sheriff',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7d/Prism_II_Stinger.png/revision/latest?cb=20210708104833',
      rarity: 'Select',
      bundle: 'Prism II',
      weapon: 'Stinger',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Prism_II_Bucky.png/revision/latest?cb=20210708104815',
      rarity: 'Select',
      bundle: 'Prism II',
      weapon: 'Bucky',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/8e/Prism_II_Vandal.png/revision/latest?cb=20210708104847',
      rarity: 'Select',
      bundle: 'Prism II',
      weapon: 'Vandal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/dc/Horizon_Frenzy.png/revision/latest?cb=20210708104931',
      rarity: 'Deluxe',
      bundle: 'Horizon',
      weapon: 'Frenzy',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/82/Horizon_Spectre.png/revision/latest?cb=20210708104951',
      rarity: 'Deluxe',
      bundle: 'Horizon',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Horizon_Bucky.png/revision/latest?cb=20210708104940',
      rarity: 'Deluxe',
      bundle: 'Horizon',
      weapon: 'Bucky',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a7/Horizon_Bulldog.png/revision/latest?cb=20210708105002',
      rarity: 'Deluxe',
      bundle: 'Horizon',
      weapon: 'Bulldog',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/8a/Horizon_Vandal.png/revision/latest?cb=20210708105011',
      rarity: 'Deluxe',
      bundle: 'Horizon',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/65/Glitchpop_Classic.png/revision/latest?cb=20210708105113',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Classic',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/74/Glitchpop_Phantom.png/revision/latest?cb=20210708105123',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ab/Glitchpop_Vandal.png/revision/latest?cb=20210708105142',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e4/Glitchpop_Operator.png/revision/latest?cb=20210708105151',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Operator',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/01/Glitchpop_Axe.png/revision/latest?cb=20210708105045',
      rarity: 'Exclusive',
      bundle: 'Glitchpop',
      weapon: 'Axe',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/1b/Celestial_Frenzy.png/revision/latest?cb=20210310001652',
      rarity: 'Premium',
      bundle: 'Celestial',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/00/Celestial_Judge.png/revision/latest?cb=20210310001735',
      rarity: 'Premium',
      bundle: 'Celestial',
      weapon: 'Judge',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6e/Celestial_Phantom.png/revision/latest?cb=20210310001841',
      rarity: 'Premium',
      bundle: 'Celestial',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/03/Celestial_Ares.png/revision/latest?cb=20210310001814',
      rarity: 'Premium',
      bundle: 'Celestial',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c0/Celestial_Fan.png/revision/latest?cb=20210708105253',
      rarity: 'Premium',
      bundle: 'Celestial',
      weapon: 'Fan',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/da/VALORANT_Go%21_Vol._1_Ghost.png/revision/latest?cb=20210708105415',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 1',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d8/VALORANT_Go%21_Vol._1_Spectre.png/revision/latest?cb=20210708105439',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 1',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b7/VALORANT_Go%21_Vol._1_Guardian.png/revision/latest?cb=20210708105502',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 1',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/07/VALORANT_Go%21_Vol._1_Phantom.png/revision/latest?cb=20210708105521',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 1',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/77/VALORANT_Go%21_Vol._1_Knife.png/revision/latest?cb=20210708105355',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 1',
      weapon: 'Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a4/Prime_2.0_Frenzy.png/revision/latest?cb=20210707191254',
      rarity: 'Premium',
      bundle: 'Prime//2.0',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/18/Prime_2.0_Bucky.png/revision/latest?cb=20210707191252',
      rarity: 'Premium',
      bundle: 'Prime//2.0',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Prime_2.0_Phantom.png/revision/latest?cb=20210707191257',
      rarity: 'Premium',
      bundle: 'Prime//2.0',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/de/Prime_2.0_Odin.png/revision/latest?cb=20210707191256',
      rarity: 'Premium',
      bundle: 'Prime//2.0',
      weapon: 'Odin',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cf/Prime_2.0_Karambit.png/revision/latest?cb=20210707191255',
      rarity: 'Premium',
      bundle: 'Prime//2.0',
      weapon: 'Karambit',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b9/Infantry_Ghost.png/revision/latest?cb=20210708105646',
      rarity: 'Select',
      bundle: 'Infantry',
      weapon: 'Ghost',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7f/Infantry_Spectre.png/revision/latest?cb=20210708105709',
      rarity: 'Select',
      bundle: 'Infantry',
      weapon: 'Spectre',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/1b/Infantry_Guardian.png/revision/latest?cb=20210708105735',
      rarity: 'Select',
      bundle: 'Infantry',
      weapon: 'Guardian',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7d/Infantry_Operator.png/revision/latest?cb=20210708105816',
      rarity: 'Select',
      bundle: 'Infantry',
      weapon: 'Operator',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/56/Infantry_Ares.png/revision/latest?cb=20210708105756',
      rarity: 'Select',
      bundle: 'Infantry',
      weapon: 'Ares',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/92/Magepunk_Ghost.png/revision/latest?cb=20210708121456',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/8b/Magepunk_Spectre.png/revision/latest?cb=20210708121552',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e4/Magepunk_Bucky.png/revision/latest?cb=20210708121613',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5a/Magepunk_Marshal.png/revision/latest?cb=20210708121637',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/34/Magepunk_Electroblade.png/revision/latest?cb=20210708121531',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Electroblade',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9f/Silvanus_Sheriff.png/revision/latest?cb=20210708121711',
      rarity: 'Deluxe',
      bundle: 'Silvanus',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/11/Silvanus_Stinger.png/revision/latest?cb=20210708121739',
      rarity: 'Deluxe',
      bundle: 'Silvanus',
      weapon: 'Stinger',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/70/Silvanus_Phantom.png/revision/latest?cb=20210708121802',
      rarity: 'Deluxe',
      bundle: 'Silvanus',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/ff/Silvanus_Vandal.png/revision/latest?cb=20210708121822',
      rarity: 'Deluxe',
      bundle: 'Silvanus',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/73/Silvanus_Operator.png/revision/latest?cb=20210708121848',
      rarity: 'Deluxe',
      bundle: 'Silvanus',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/89/Forsaken_Classic.png/revision/latest?cb=20210708122017',
      rarity: 'Premium',
      bundle: 'Forsaken',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/02/Forsaken_Spectre.png/revision/latest?cb=20210708122041',
      rarity: 'Premium',
      bundle: 'Forsaken',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/68/Forsaken_Vandal.png/revision/latest?cb=20210708122104',
      rarity: 'Premium',
      bundle: 'Forsaken',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d4/Forsaken_Operator.png/revision/latest?cb=20210708121929',
      rarity: 'Premium',
      bundle: 'Forsaken',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4c/Forsaken_Ritual_Blade.png/revision/latest?cb=20210708121951',
      rarity: 'Premium',
      bundle: 'Forsaken',
      weapon: 'Ritual Blade',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/49/Minima_Sheriff.png/revision/latest?cb=20210708122330',
      rarity: 'Deluxe',
      bundle: 'Minima',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f6/Minima_Spectre.png/revision/latest?cb=20210708122405',
      rarity: 'Deluxe',
      bundle: 'Minima',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/89/Minima_Phantom.png/revision/latest?cb=20210708122423',
      rarity: 'Deluxe',
      bundle: 'Minima',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cf/Minima_Operator.png/revision/latest?cb=20210708122442',
      rarity: 'Deluxe',
      bundle: 'Minima',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cb/Minima_Ares.png/revision/latest?cb=20210708122501',
      rarity: 'Deluxe',
      bundle: 'Minima',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f9/Tethered_Realms_Ghost.png/revision/latest?cb=20210708122541',
      rarity: 'Premium',
      bundle: 'Tethered Realms',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d7/Tethered_Realms_Guardian.png/revision/latest?cb=20210708122608',
      rarity: 'Premium',
      bundle: 'Tethered Realms',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e7/Tethered_Realms_Vandal.png/revision/latest?cb=20210708122627',
      rarity: 'Premium',
      bundle: 'Tethered Realms',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b8/Tethered_Realms_Operator.png/revision/latest?cb=20210708122648',
      rarity: 'Premium',
      bundle: 'Tethered Realms',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f0/Tethered_Realms_Prosperity.png/revision/latest?cb=20210708122713',
      rarity: 'Premium',
      bundle: 'Tethered Realms',
      weapon: 'Prosperity',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c8/Origin_Frenzy.png/revision/latest?cb=20210708122818',
      rarity: 'Premium',
      bundle: 'Origin',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/2e/Origin_Bucky.png/revision/latest?cb=20210708122847',
      rarity: 'Premium',
      bundle: 'Origin',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5b/Origin_Vandal.png/revision/latest?cb=20210708122917',
      rarity: 'Premium',
      bundle: 'Origin',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/da/Origin_Operator.png/revision/latest?cb=20210708122941',
      rarity: 'Premium',
      bundle: 'Origin',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/98/Origin_Crescent_Blade.png/revision/latest?cb=20210707185755',
      rarity: 'Premium',
      bundle: 'Origin',
      weapon: 'Crescent Blade',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6b/Ruination_Ghost.png/revision/latest?cb=20210707184809',
      rarity: 'Exclusive',
      bundle: 'Ruination',
      weapon: 'Ghost',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c6/Ruination_Spectre.png/revision/latest?cb=20210707184931',
      rarity: 'Exclusive',
      bundle: 'Ruination',
      weapon: 'Spectre',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3f/Ruination_Guardian.png/revision/latest?cb=20210707184826',
      rarity: 'Exclusive',
      bundle: 'Ruination',
      weapon: 'Guardian',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7c/Ruination_Phantom.png/revision/latest?cb=20210707184913',
      rarity: 'Exclusive',
      bundle: 'Ruination',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/b/bb/Ruination_Broken_Blade_Of_The_Ruined_King.png/revision/latest?cb=20210712114145',
      rarity: 'Exclusive',
      bundle: 'Ruination',
      weapon: 'Broken Blade Of The Ruined King',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3d/Sentinels_Of_Light_Sheriff.png/revision/latest?cb=20210720175659',
      rarity: 'Exclusive',
      bundle: 'Sentinels of Light',
      weapon: 'Sheriff',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/69/Sentinels_Of_Light_Vandal.png/revision/latest?cb=20210720175714',
      rarity: 'Exclusive',
      bundle: 'Sentinels of Light',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/ba/Sentinels_Of_Light_Operator.png/revision/latest?cb=20210720175643',
      rarity: 'Exclusive',
      bundle: 'Sentinels of Light',
      weapon: 'Operator',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/da/Sentinels_Of_Light_Ares.png/revision/latest?cb=20210720175610',
      rarity: 'Exclusive',
      bundle: 'Sentinels of Light',
      weapon: 'Ares',
      price: 2175,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/9/93/Sentinels_Of_Light_Relic_Of_The_Sentinel.png/revision/latest?cb=20210720175627',
      rarity: 'Exclusive',
      bundle: 'Sentinels of Light',
      weapon: 'Relic of the Sentinel',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e7/Recon_Ghost.png/revision/latest?cb=20210824165144',
      rarity: 'Premium',
      bundle: 'Recon',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/18/Recon_Spectre.png/revision/latest?cb=20210824165144',
      rarity: 'Premium',
      bundle: 'Recon',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6e/Recon_Guardian.png/revision/latest?cb=20210824165145',
      rarity: 'Premium',
      bundle: 'Recon',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b3/Recon_Phantom.png/revision/latest?cb=20210824165144',
      rarity: 'Premium',
      bundle: 'Recon',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/aa/Recon_Balisong.png/revision/latest?cb=20210824165142',
      rarity: 'Premium',
      bundle: 'Recon',
      weapon: 'Balisong',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/df/SPECTRUM_Classic.png/revision/latest?cb=20210908214458',
      rarity: 'Exclusive',
      bundle: 'Spectrum',
      weapon: 'Classic',
      price: 2675,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0d/SPECTRUM_Bulldog.png/revision/latest?cb=20210908214451',
      rarity: 'Exclusive',
      bundle: 'Spectrum',
      weapon: 'Bulldog',
      price: 2675,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f5/SPECTRUM_Guardian.png/revision/latest?cb=20210908214456',
      rarity: 'Exclusive',
      bundle: 'Spectrum',
      weapon: 'Guardian',
      price: 2675,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f4/SPECTRUM_Phantom.png/revision/latest?cb=20210908214445',
      rarity: 'Exclusive',
      bundle: 'Spectrum',
      weapon: 'Phantom',
      price: 2675,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e7/SPECTRUM_Waveform.png/revision/latest?cb=20210908214448',
      rarity: 'Exclusive',
      bundle: 'Spectrum',
      weapon: 'Waveform',
      price: 5350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/33/VALORANT_Go%21_Vol._2_Classic.png/revision/latest?cb=20210921174840',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 2',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5b/VALORANT_Go%21_Vol._2_Vandal.png/revision/latest?cb=20210921174824',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 2',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/90/VALORANT_Go%21_Vol._2_Operator.png/revision/latest?cb=20210921174830',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 2',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/87/VALORANT_Go%21_Vol._2_Ares.png/revision/latest?cb=20210921174844',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 2',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/1e/Yoru%27s_Stylish_Butterfly_Comb.png/revision/latest?cb=20210921174835',
      rarity: 'Premium',
      bundle: 'VALORANT Go! Vol. 2',
      weapon: "Yoru's Stylish Butterfly Comb",
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/98/RGX_11z_Pro_Frenzy.png/revision/latest?cb=20211005172517',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Frenzy',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/29/RGX_11z_Pro_Stinger.png/revision/latest?cb=20211005172557',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Stinger',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/55/RGX_11z_Pro_Guardian.png/revision/latest?cb=20211005172538',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Guardian',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/41/RGX_11z_Pro_Vandal.png/revision/latest?cb=20211005172619',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/15/RGX_11z_Pro_Blade.png/revision/latest?cb=20211005172436',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Blade',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f8/Nunca_Olvidados_Frenzy.png/revision/latest?cb=20211019175756',
      rarity: 'Deluxe',
      bundle: 'Nunca Olvidados',
      weapon: 'Frenzy',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0f/Nunca_Olvidados_Bulldog.png/revision/latest?cb=20211019175809',
      rarity: 'Deluxe',
      bundle: 'Nunca Olvidados',
      weapon: 'Bulldog',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/17/Nunca_Olvidados_Vandal.png/revision/latest?cb=20211019175713',
      rarity: 'Deluxe',
      bundle: 'Nunca Olvidados',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c6/Nunca_Olvidados_Ares.png/revision/latest?cb=20211019175820',
      rarity: 'Deluxe',
      bundle: 'Nunca Olvidados',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4c/Nunca_Olvidados_Catrina.png/revision/latest?cb=20211019175838',
      rarity: 'Deluxe',
      bundle: 'Nunca Olvidados',
      weapon: 'Catrina',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/75/Radiant_Crisis_001_Classic.png/revision/latest?cb=20211102175411',
      rarity: 'Premium',
      bundle: 'Radiant Crisis 001',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ac/Radiant_Crisis_001_Spectre.png/revision/latest?cb=20211102175420',
      rarity: 'Premium',
      bundle: 'Radiant Crisis 001',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Radiant_Crisis_001_Bucky.png/revision/latest?cb=20211102175407',
      rarity: 'Premium',
      bundle: 'Radiant Crisis 001',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/00/Radiant_Crisis_001_Phantom.png/revision/latest?cb=20211102175415',
      rarity: 'Premium',
      bundle: 'Radiant Crisis 001',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3f/Radiant_Crisis_001_Baseball_Bat.png/revision/latest?cb=20211102175403',
      rarity: 'Premium',
      bundle: 'Radiant Crisis 001',
      weapon: 'Baseball Bat',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/2f/Magepunk_Sheriff.png/revision/latest?cb=20211119105628',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Sheriff',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a6/Magepunk_Guardian.png/revision/latest?cb=20211119110014',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Magepunk_Operator.png/revision/latest?cb=20211119105827',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/31/Magepunk_Ares.png/revision/latest?cb=20211119110057',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/98/Magepunk_Shock_Gauntlet.png/revision/latest?cb=20211119105506',
      rarity: 'Premium',
      bundle: 'Magepunk',
      weapon: 'Shock Gauntlet',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/ee/Snowfall_Classic.png/revision/latest?cb=20211207184332',
      rarity: 'Deluxe',
      bundle: 'Snowfall',
      weapon: 'Classic',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/76/Snowfall_Judge.png/revision/latest?cb=20211207184337',
      rarity: 'Deluxe',
      bundle: 'Snowfall',
      weapon: 'Judge',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/78/Snowfall_Phantom.png/revision/latest?cb=20211207184341',
      rarity: 'Deluxe',
      bundle: 'Snowfall',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/25/Snowfall_Ares.png/revision/latest?cb=20211207184326',
      rarity: 'Deluxe',
      bundle: 'Snowfall',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e1/Snowfall_Wand.png/revision/latest?cb=20211207184346',
      rarity: 'Deluxe',
      bundle: 'Snowfall',
      weapon: 'Wand',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Protocol_781-A_Sheriff.png/revision/latest?cb=20220113063244',
      rarity: 'Ultra',
      bundle: 'Protocol 781-A',
      weapon: 'Sheriff',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e9/Protocol_781-A_Spectre.png/revision/latest?cb=20220113063244',
      rarity: 'Ultra',
      bundle: 'Protocol 781-A',
      weapon: 'Spectre',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e2/Protocol_781-A_Bulldog.png/revision/latest?cb=20220113063243',
      rarity: 'Ultra',
      bundle: 'Protocol 781-A',
      weapon: 'Bulldog',
      price: 2475,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/ce/Protocol_781-A_Phantom.png/revision/latest?cb=20220113063243',
      rarity: 'Ultra',
      bundle: 'Protocol 781-A',
      weapon: 'Phantom',
      price: 2475,
    },
    {
      img_url:
        'https://static.wikia.nocookie.net/valorant/images/8/8a/Protocol_781-A_Personal_Administrative_Melee_Unit.png/revision/latest?cb=20220113063243',
      rarity: 'Ultra',
      bundle: 'Protocol 781-A',
      weapon: 'Personal Administrative Melee Unit',
      price: 4950,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4c/Tigris_Shorty.png/revision/latest?cb=20220201214711',
      rarity: 'Deluxe',
      bundle: 'Tigris',
      weapon: 'Shorty',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/68/Tigris_Spectre.png/revision/latest?cb=20220201214714',
      rarity: 'Deluxe',
      bundle: 'Tigris',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/79/Tigris_Phantom.png/revision/latest?cb=20220201214707',
      rarity: 'Deluxe',
      bundle: 'Tigris',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b5/Tigris_Operator.png/revision/latest?cb=20220201214703',
      rarity: 'Deluxe',
      bundle: 'Tigris',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fd/Tigris_Hu_Else.png/revision/latest?cb=20220201214658',
      rarity: 'Deluxe',
      bundle: 'Tigris',
      weapon: 'Hu Else',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/8a/Undercity_Classic.png/revision/latest?cb=20220217141353',
      rarity: 'Premium',
      bundle: 'Undercity',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/37/Undercity_Judge.png/revision/latest?cb=20220217141303',
      rarity: 'Premium',
      bundle: 'Undercity',
      weapon: 'Judge',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/27/Undercity_Bulldog.png/revision/latest?cb=20220217141413',
      rarity: 'Premium',
      bundle: 'Undercity',
      weapon: 'Bulldog',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d7/Undercity_Phantom.png/revision/latest?cb=20220217141237',
      rarity: 'Premium',
      bundle: 'Undercity',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/15/Undercity_Hack.png/revision/latest?cb=20220217141344',
      rarity: 'Premium',
      bundle: 'Undercity',
      weapon: 'Hack',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/46/Gaia%27s_Vengeance_Ghost.png/revision/latest?cb=20220302170019',
      rarity: 'Premium',
      bundle: "Gaia's Vengeance",
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/19/Gaia%27s_Vengeance_Guardian.png/revision/latest?cb=20220302170019',
      rarity: 'Premium',
      bundle: "Gaia's Vengeance",
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0c/Gaia%27s_Vengeance_Vandal.png/revision/latest?cb=20220302170020',
      rarity: 'Premium',
      bundle: "Gaia's Vengeance",
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c0/Gaia%27s_Vengeance_Marshal.png/revision/latest?cb=20220302170019',
      rarity: 'Premium',
      bundle: "Gaia's Vengeance",
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/56/Gaia%27s_Wrath.png/revision/latest?cb=20220302170020',
      rarity: 'Premium',
      bundle: "Gaia's Vengeance",
      weapon: "Gaia's Wrath",
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/62/Team_Ace_Frenzy.png/revision/latest?cb=20220302170021',
      rarity: 'Deluxe',
      bundle: 'Team Ace',
      weapon: 'Frenzy',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/88/Team_Ace_Judge.png/revision/latest?cb=20220302170021',
      rarity: 'Deluxe',
      bundle: 'Team Ace',
      weapon: 'Judge',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/88/Team_Ace_Phantom.png/revision/latest?cb=20220302170021',
      rarity: 'Deluxe',
      bundle: 'Team Ace',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f8/Team_Ace_Vandal.png/revision/latest?cb=20220302170021',
      rarity: 'Deluxe',
      bundle: 'Team Ace',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ab/Team_Ace_Operator.png/revision/latest?cb=20220302170021',
      rarity: 'Deluxe',
      bundle: 'Team Ace',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/72/Endeavour_Ghost.png/revision/latest?cb=20220323151705',
      rarity: 'Select',
      bundle: 'Endeavour',
      weapon: 'Ghost',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f8/Endeavour_Bulldog.png/revision/latest?cb=20220323151642',
      rarity: 'Select',
      bundle: 'Endeavour',
      weapon: 'Bulldog',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/2a/Endeavour_Vandal.png/revision/latest?cb=20220323151611',
      rarity: 'Select',
      bundle: 'Endeavour',
      weapon: 'Vandal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/45/Endeavour_Operator.png/revision/latest?cb=20220323151653',
      rarity: 'Select',
      bundle: 'Endeavour',
      weapon: 'Operator',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/54/Endeavour_Ares.png/revision/latest?cb=20220323151720',
      rarity: 'Select',
      bundle: 'Endeavour',
      weapon: 'Ares',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d5/Doodle_Buds_Shorty.png/revision/latest?cb=20230425140004',
      rarity: 'Premium',
      bundle: 'Doodle Buds',
      weapon: 'Shorty',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/ca/Doodle_Buds_Stinger.png/revision/latest?cb=20220415131722',
      rarity: 'Premium',
      bundle: 'Doodle Buds',
      weapon: 'Stinger',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/59/Doodle_Buds_Phantom.png/revision/latest?cb=20220415131700',
      rarity: 'Premium',
      bundle: 'Doodle Buds',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f8/Doodle_Buds_Marshal.png/revision/latest?cb=20220415131423',
      rarity: 'Premium',
      bundle: 'Doodle Buds',
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/be/Doodle_Buds_Ares.png/revision/latest?cb=20220415131311',
      rarity: 'Premium',
      bundle: 'Doodle Buds',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/87/RGX_11z_Pro_Classic.png/revision/latest?cb=20220427142733',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Classic',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7b/RGX_11z_Pro_Spectre.png/revision/latest?cb=20220427142747',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Spectre',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/bb/RGX_11z_Pro_Phantom.png/revision/latest?cb=20220427142744',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4c/RGX_11z_Pro_Operator.png/revision/latest?cb=20220427142740',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Operator',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/da/RGX_11z_Pro_Firefly.png/revision/latest?cb=20220427142737',
      rarity: 'Exclusive',
      bundle: 'RGX 11z Pro',
      weapon: 'Firefly',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d0/Titanmail_Frenzy.png/revision/latest?cb=20220510155559',
      rarity: 'Deluxe',
      bundle: 'Titanmail',
      weapon: 'Frenzy',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/46/Titanmail_Bucky.png/revision/latest?cb=20220510155558',
      rarity: 'Deluxe',
      bundle: 'Titanmail',
      weapon: 'Bucky',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/09/Titanmail_Vandal.png/revision/latest?cb=20220510155601',
      rarity: 'Deluxe',
      bundle: 'Titanmail',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/93/Titanmail_Ares.png/revision/latest?cb=20220510155557',
      rarity: 'Deluxe',
      bundle: 'Titanmail',
      weapon: 'Ares',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/60/Titanmail_Mace.png/revision/latest?cb=20220510155600',
      rarity: 'Deluxe',
      bundle: 'Titanmail',
      weapon: 'Mace',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/48/Neptune_Shorty.png/revision/latest?cb=20220524173532',
      rarity: 'Premium',
      bundle: 'Neptune',
      weapon: 'Shorty',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4e/Neptune_Spectre.png/revision/latest?cb=20220524173534',
      rarity: 'Premium',
      bundle: 'Neptune',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a5/Neptune_Guardian.png/revision/latest?cb=20220524173530',
      rarity: 'Premium',
      bundle: 'Neptune',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fe/Neptune_Vandal.png/revision/latest?cb=20220524173536',
      rarity: 'Premium',
      bundle: 'Neptune',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/90/Neptune_Anchor.png/revision/latest?cb=20220524173527',
      rarity: 'Premium',
      bundle: 'Neptune',
      weapon: 'Anchor',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/17/Xenohunter_Frenzy.png/revision/latest?cb=20220607160039',
      rarity: 'Premium',
      bundle: 'Xenohunter',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e1/Xenohunter_Bucky.png/revision/latest?cb=20220607160040',
      rarity: 'Premium',
      bundle: 'Xenohunter',
      weapon: 'Bucky',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0a/Xenohunter_Phantom.png/revision/latest?cb=20220607160043',
      rarity: 'Premium',
      bundle: 'Xenohunter',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/70/Xenohunter_Odin.png/revision/latest?cb=20220607160044',
      rarity: 'Premium',
      bundle: 'Xenohunter',
      weapon: 'Odin',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d0/Xenohunter_Knife.png/revision/latest?cb=20220607160041',
      rarity: 'Premium',
      bundle: 'Xenohunter',
      weapon: 'Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/78/Prelude_to_Chaos_Shorty.png/revision/latest?cb=20220622133017',
      rarity: 'Exclusive',
      bundle: 'Prelude to Chaos',
      weapon: 'Shorty',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/88/Prelude_to_Chaos_Stinger.png/revision/latest?cb=20220622133021',
      rarity: 'Exclusive',
      bundle: 'Prelude to Chaos',
      weapon: 'Stinger',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a8/Prelude_to_Chaos_Vandal.png/revision/latest?cb=20220622133025',
      rarity: 'Exclusive',
      bundle: 'Prelude to Chaos',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/48/Prelude_to_Chaos_Operator.png/revision/latest?cb=20220622133013',
      rarity: 'Exclusive',
      bundle: 'Prelude to Chaos',
      weapon: 'Operator',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4b/Blade_of_Chaos.png/revision/latest?cb=20220622133010',
      rarity: 'Exclusive',
      bundle: 'Prelude to Chaos',
      weapon: 'Blade of Chaos',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d1/Sarmad_Frenzy.png/revision/latest?cb=20220712164224',
      rarity: 'Deluxe',
      bundle: 'Sarmad',
      weapon: 'Frenzy',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b0/Sarmad_Spectre.png/revision/latest?cb=20220712164226',
      rarity: 'Deluxe',
      bundle: 'Sarmad',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fa/Sarmad_Phantom.png/revision/latest?cb=20220712164225',
      rarity: 'Deluxe',
      bundle: 'Sarmad',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/70/Sarmad_Vandal.png/revision/latest?cb=20220712164227',
      rarity: 'Deluxe',
      bundle: 'Sarmad',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d3/Blade_of_Serket.png/revision/latest?cb=20220712164222',
      rarity: 'Deluxe',
      bundle: 'Sarmad',
      weapon: 'Blade of Serket',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/94/Reaver%2C_EP_5_Ghost.png/revision/latest?cb=20220809131733',
      rarity: 'Premium',
      bundle: 'Reaver, EP 5',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/1e/Reaver%2C_EP_5_Spectre.png/revision/latest?cb=20220809131747',
      rarity: 'Premium',
      bundle: 'Reaver, EP 5',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/7a/Reaver%2C_EP_5_Phantom.png/revision/latest?cb=20220809131744',
      rarity: 'Premium',
      bundle: 'Reaver, EP 5',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5c/Reaver%2C_EP_5_Odin.png/revision/latest?cb=20220809131740',
      rarity: 'Premium',
      bundle: 'Reaver, EP 5',
      weapon: 'Odin',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0d/Reaver%2C_EP_5_Karambit.png/revision/latest?cb=20220809131737',
      rarity: 'Premium',
      bundle: 'Reaver, EP 5',
      weapon: 'Karambit',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/95/Kohaku_%26_Matsuba_Classic.png/revision/latest?cb=20220907171539',
      rarity: 'Deluxe',
      bundle: 'Kohaku & Matsuba',
      weapon: 'Classic',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/77/Kohaku_%26_Matsuba_Judge.png/revision/latest?cb=20220907171541',
      rarity: 'Deluxe',
      bundle: 'Kohaku & Matsuba',
      weapon: 'Judge',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/2c/Kohaku_%26_Matsuba_Phantom.png/revision/latest?cb=20220907171545',
      rarity: 'Deluxe',
      bundle: 'Kohaku & Matsuba',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3b/Kohaku_%26_Matsuba_Operator.png/revision/latest?cb=20220907171543',
      rarity: 'Deluxe',
      bundle: 'Kohaku & Matsuba',
      weapon: 'Operator',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/81/Equilibrium.png/revision/latest?cb=20220907171537',
      rarity: 'Deluxe',
      bundle: 'Kohaku & Matsuba',
      weapon: 'Equilibrium',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/69/ChronoVoid_Sheriff.png/revision/latest?cb=20220920131634',
      rarity: 'Exclusive',
      bundle: 'ChronoVoid',
      weapon: 'Sheriff',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/ae/ChronoVoid_Judge.png/revision/latest?cb=20220920131626',
      rarity: 'Exclusive',
      bundle: 'ChronoVoid',
      weapon: 'Judge',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/ca/ChronoVoid_Phantom.png/revision/latest?cb=20220920131630',
      rarity: 'Exclusive',
      bundle: 'ChronoVoid',
      weapon: 'Phantom',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/93/ChronoVoid_Vandal.png/revision/latest?cb=20220920131637',
      rarity: 'Exclusive',
      bundle: 'ChronoVoid',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0d/Terminus_A_Quo.png/revision/latest?cb=20220920131642',
      rarity: 'Exclusive',
      bundle: 'ChronoVoid',
      weapon: 'Terminus A Quo',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/42/Crimsonbeast_Sheriff.png/revision/latest?cb=20221004165139',
      rarity: 'Premium',
      bundle: 'Crimsonbeast',
      weapon: 'Sheriff',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/79/Crimsonbeast_Judge.png/revision/latest?cb=20221004165137',
      rarity: 'Premium',
      bundle: 'Crimsonbeast',
      weapon: 'Judge',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/cf/Crimsonbeast_Vandal.png/revision/latest?cb=20221004165140',
      rarity: 'Premium',
      bundle: 'Crimsonbeast',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5c/Crimsonbeast_Marshal.png/revision/latest?cb=20221004165138',
      rarity: 'Premium',
      bundle: 'Crimsonbeast',
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/42/Crimsonbeast_Hammer.png/revision/latest?cb=20221004165136',
      rarity: 'Premium',
      bundle: 'Crimsonbeast',
      weapon: 'Hammer',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9f/Ion_Frenzy.png/revision/latest?cb=20221018133136',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4b/Ion_Spectre.png/revision/latest?cb=20221018133201',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e8/Ion_Vandal.png/revision/latest?cb=20221018133212',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c3/Ion_Ares.png/revision/latest?cb=20221018133123',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a6/Ion_Karambit.png/revision/latest?cb=20221018133149',
      rarity: 'Premium',
      bundle: 'Ion',
      weapon: 'Karambit',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d7/Soulstrife_Ghost.png/revision/latest?cb=20221101155513',
      rarity: 'Premium',
      bundle: 'Soulstrife',
      weapon: 'Ghost',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/9a/Soulstrife_Spectre.png/revision/latest?cb=20221101155517',
      rarity: 'Premium',
      bundle: 'Soulstrife',
      weapon: 'Spectre',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/ba/Soulstrife_Guardian.png/revision/latest?cb=20221101155514',
      rarity: 'Premium',
      bundle: 'Soulstrife',
      weapon: 'Guardian',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/99/Soulstrife_Phantom.png/revision/latest?cb=20221101155515',
      rarity: 'Premium',
      bundle: 'Soulstrife',
      weapon: 'Phantom',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/00/Soulstrife_Scythe.png/revision/latest?cb=20221101155516',
      rarity: 'Premium',
      bundle: 'Soulstrife',
      weapon: 'Scythe',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/ec/Abyssal_Sheriff.png/revision/latest?cb=20221115170802',
      rarity: 'Deluxe',
      bundle: 'Abyssal',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/61/Abyssal_Spectre.png/revision/latest?cb=20221115170803',
      rarity: 'Deluxe',
      bundle: 'Abyssal',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a3/Abyssal_Guardian.png/revision/latest?cb=20221115170800',
      rarity: 'Deluxe',
      bundle: 'Abyssal',
      weapon: 'Guardian',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/95/Abyssal_Phantom.png/revision/latest?cb=20221115170801',
      rarity: 'Deluxe',
      bundle: 'Abyssal',
      weapon: 'Phantom',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/87/Caeruleus.png/revision/latest?cb=20221115170804',
      rarity: 'Deluxe',
      bundle: 'Abyssal',
      weapon: 'Caeruleus',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c9/Cryostasis_Classic.png/revision/latest?cb=20221206165303',
      rarity: 'Premium',
      bundle: 'Cryostasis',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/59/Cryostasis_Bulldog.png/revision/latest?cb=20221206165302',
      rarity: 'Premium',
      bundle: 'Cryostasis',
      weapon: 'Bulldog',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/01/Cryostasis_Vandal.png/revision/latest?cb=20221206165306',
      rarity: 'Premium',
      bundle: 'Cryostasis',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3e/Cryostasis_Operator.png/revision/latest?cb=20221206165305',
      rarity: 'Premium',
      bundle: 'Cryostasis',
      weapon: 'Operator',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/f3/Cryostasis_Impact_Drill.png/revision/latest?cb=20221206165304',
      rarity: 'Premium',
      bundle: 'Cryostasis',
      weapon: 'Impact Drill',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e4/Araxys_Shorty.png/revision/latest?cb=20230110150822',
      rarity: 'Exclusive',
      bundle: 'Araxys',
      weapon: 'Shorty',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/2/24/Araxys_Bulldog.png/revision/latest?cb=20230110150814',
      rarity: 'Exclusive',
      bundle: 'Araxys',
      weapon: 'Bulldog',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e1/Araxys_Vandal.png/revision/latest?cb=20230110150827',
      rarity: 'Exclusive',
      bundle: 'Araxys',
      weapon: 'Vandal',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fe/Araxys_Operator.png/revision/latest?cb=20230110150818',
      rarity: 'Exclusive',
      bundle: 'Araxys',
      weapon: 'Operator',
      price: 2175,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/07/Araxys_Bio_Harvester.png/revision/latest?cb=20230110150809',
      rarity: 'Exclusive',
      bundle: 'Araxys',
      weapon: 'Bio Harvester',
      price: 4350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5d/Luna_Ghost.png/revision/latest?cb=20230118182530',
      rarity: 'Deluxe',
      bundle: 'Luna',
      weapon: 'Ghost',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/65/Luna_Spectre.png/revision/latest?cb=20230118182534',
      rarity: 'Deluxe',
      bundle: 'Luna',
      weapon: 'Spectre',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/06/Luna_Vandal.png/revision/latest?cb=20230118182535',
      rarity: 'Deluxe',
      bundle: 'Luna',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6e/Luna_Marshal.png/revision/latest?cb=20230118182533',
      rarity: 'Deluxe',
      bundle: 'Luna',
      weapon: 'Marshal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a5/Luna%27s_Descent.png/revision/latest?cb=20230118182529',
      rarity: 'Deluxe',
      bundle: 'Luna',
      weapon: "Luna's Descent",
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c5/Reverie_Classic.png/revision/latest?cb=20230214163046',
      rarity: 'Select',
      bundle: 'Reverie',
      weapon: 'Classic',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6b/Reverie_Guardian.png/revision/latest?cb=20230214163046',
      rarity: 'Select',
      bundle: 'Reverie',
      weapon: 'Guardian',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/c/c2/Reverie_Phantom.png/revision/latest?cb=20230214163048',
      rarity: 'Select',
      bundle: 'Reverie',
      weapon: 'Phantom',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/1/19/Reverie_Marshal.png/revision/latest?cb=20230214163047',
      rarity: 'Select',
      bundle: 'Reverie',
      weapon: 'Marshal',
      price: 875,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/57/Reverie_Sword.png/revision/latest?cb=20230214163044',
      rarity: 'Select',
      bundle: 'Reverie',
      weapon: 'Sword',
      price: 1750,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/a/a8/Oni_Frenzy.png/revision/latest?cb=20230307165624',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Frenzy',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/0b/Oni_Bulldog.png/revision/latest?cb=20230307165619',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Bulldog',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/3b/Oni_Vandal.png/revision/latest?cb=20230307165629',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/69/Oni_Ares.png/revision/latest?cb=20230307165614',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Ares',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/d6/Onimaru_Kunitsuna.png/revision/latest?cb=20230307165634',
      rarity: 'Premium',
      bundle: 'Oni',
      weapon: 'Onimaru Kunitsuna',
      price: 5350,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/eb/Altitude_Sheriff.png/revision/latest?cb=20230328154319',
      rarity: 'Deluxe',
      bundle: 'Altitude',
      weapon: 'Sheriff',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/d/db/Altitude_Bucky.png/revision/latest?cb=20230328154316',
      rarity: 'Deluxe',
      bundle: 'Altitude',
      weapon: 'Bucky',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/8/84/Altitude_Vandal.png/revision/latest?cb=20230328154315',
      rarity: 'Deluxe',
      bundle: 'Altitude',
      weapon: 'Vandal',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/f/fc/Altitude_Odin.png/revision/latest?cb=20230328154318',
      rarity: 'Deluxe',
      bundle: 'Altitude',
      weapon: 'Odin',
      price: 1275,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/7/78/Altitude_Knuckle_Knife.png/revision/latest?cb=20230328154317',
      rarity: 'Deluxe',
      bundle: 'Altitude',
      weapon: 'Knuckle Knife',
      price: 2550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/e/e8/Black.Market_Classic.png/revision/latest?cb=20230411161450',
      rarity: 'Premium',
      bundle: 'Black.Market',
      weapon: 'Classic',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/4/4b/Black.Market_Bulldog.png/revision/latest?cb=20230411161448',
      rarity: 'Premium',
      bundle: 'Black.Market',
      weapon: 'Bulldog',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/3/31/Black.Market_Vandal.png/revision/latest?cb=20230411161447',
      rarity: 'Premium',
      bundle: 'Black.Market',
      weapon: 'Vandal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/08/Black.Market_Marshal.png/revision/latest?cb=20230411161451',
      rarity: 'Premium',
      bundle: 'Black.Market',
      weapon: 'Marshal',
      price: 1775,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/5f/Black.Market_Butterfly_Knife.png/revision/latest?cb=20230411161449',
      rarity: 'Premium',
      bundle: 'Black.Market',
      weapon: 'Butterfly Knife',
      price: 3550,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/0/05/Radiant_Entertainment_System_Ghost.png/revision/latest?cb=20230425141049',
      rarity: 'Ultra',
      bundle: 'Radiant Entertainment System',
      weapon: 'Ghost',
      price: 2975,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/6/6f/Radiant_Entertainment_System_Bulldog.png/revision/latest?cb=20230425141046',
      rarity: 'Ultra',
      bundle: 'Radiant Entertainment System',
      weapon: 'Bulldog',
      price: 2975,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/b/b6/Radiant_Entertainment_System_Phantom.png/revision/latest?cb=20230425141004',
      rarity: 'Ultra',
      bundle: 'Radiant Entertainment System',
      weapon: 'Phantom',
      price: 2975,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/5/53/Radiant_Entertainment_System_Operator.png/revision/latest?cb=20230425141052',
      rarity: 'Ultra',
      bundle: 'Radiant Entertainment System',
      weapon: 'Operator',
      price: 2975,
    },
    {
      img_url: 'https://static.wikia.nocookie.net/valorant/images/9/98/Power_Fist.png/revision/latest?cb=20230425141042',
      rarity: 'Ultra',
      bundle: 'Radiant Entertainment System',
      weapon: 'Power Fist',
      price: 5950,
    },
  ],
}

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    setMode: state => {
      state.mode = state.mode === 'light' ? 'dark' : 'light'
    },
    setLogin: (state, action) => {
      state.user = action.payload.user
      state.token = action.payload.token
    },
    setLogout: state => {
      state.user = null
      state.token = null
    },
    setFavoriteSkins: (state, action) => {
      if (state.user) {
        state.user.favoriteSkins = action.payload.favoriteSkins
      } else {
        console.error('error in setFavoriteSkins')
      }
    },
    setCart: (state, action) => {
      state.cart = action.payload.cart
    },
    setLikes: (state, action) => {
      state.likes = action.payload.likes
    },
  },
})

export const { setMode, setLogin, setLogout, setFavoriteSkins, setCart, setLikes } = authSlice.actions
export default authSlice.reducer
